"use client";
import { useState } from "react";
import { useResource } from "@/lib/client/use-resource";
import { apiRequest, jsonRequest } from "@/lib/client/api";
import { ResourceError } from "@/components/ui/resource-error";
type Message = { id: string; subject: string; body: string; reply: string | null; createdAt: string; user: { name: string | null; email: string | null } };
export function ContactWorkbench({ admin }: { admin: boolean }) {
 const { data, loading, error, reload } = useResource<{ messages: Message[] }>("/api/contact");
 const [pending, setPending] = useState(false); const [result, setResult] = useState("");
 async function send(form: HTMLFormElement, id?: string) { if (pending) return; const values = new FormData(form); setPending(true); setResult(""); try { await apiRequest("/api/contact", jsonRequest(id ? "PATCH" : "POST", id ? { id, reply: values.get("reply") } : { subject: values.get("subject"), body: values.get("body") })); form.reset(); setResult("訊息已送出。"); await reload(); } catch (e) { setResult(e instanceof Error ? e.message : "送出失敗"); } finally { setPending(false); } }
 return <><form className="card" onSubmit={(e) => { e.preventDefault(); void send(e.currentTarget); }}><fieldset className="dialog-fields modal-body" disabled={pending}><legend>傳送訊息給管理員</legend><label>主旨<input name="subject" required maxLength={150} /></label><label>訊息內容<textarea name="body" required maxLength={5000} rows={4} /></label><small>站內訊息，不會寄送郵件。請勿提供密碼、API key 或其他機密。</small><button className="button primary">{pending ? "傳送中…" : "傳送訊息"}</button></fieldset></form><p role="status">{result}</p><div className="page-actions"><h2>{admin ? "使用者訊息" : "我的訊息"}</h2><button className="button" disabled={loading || pending} onClick={() => void reload()}>重新整理</button></div>{error ? <ResourceError message={error} retry={reload} /> : loading ? <p role="status">載入中…</p> : !data?.messages.length ? <p>尚無訊息。</p> : data.messages.map((m) => <article className="card modal-body" key={m.id}><h3>{m.subject}</h3><small>{m.user.email} · {m.user.name} · {new Date(m.createdAt).toLocaleString("zh-TW")}</small><p style={{ whiteSpace: "pre-wrap", overflowWrap: "anywhere" }}>{m.body}</p>{m.reply ? <div><strong>管理員回覆</strong><p style={{ whiteSpace: "pre-wrap", overflowWrap: "anywhere" }}>{m.reply}</p></div> : admin ? <form onSubmit={(e) => { e.preventDefault(); void send(e.currentTarget, m.id); }}><label>回覆<textarea name="reply" required maxLength={5000} rows={3} disabled={pending} /></label><button className="button" disabled={pending}>送出回覆</button></form> : <span>等待管理員回覆</span>}</article>)}</>;
}
