"use client";
import { useState } from "react";
import { useResource } from "@/lib/client/use-resource";
import { apiRequest, jsonRequest } from "@/lib/client/api";
import { ResourceError } from "@/components/ui/resource-error";
import { Dialog } from "@/components/ui/dialog";
import type { InventoryRecord } from "@/lib/inventory/types";
type Task = { id: string; userId: string; status: string; snapshot: { zoneName: string; recordName: string; recordType: string; content: string; purpose: string; applicantUnit: string }; response: string | null; createdAt: string; respondedAt: string | null; user: { email: string | null; name: string | null } };
const labels: Record<string, string> = { PENDING: "待確認", CONFIRMED: "確認仍在使用", ISSUE: "已回報問題", CANCELLED: "已撤回" };
export function InspectionsWorkbench({ admin, actorId }: { admin: boolean; actorId: string }) {
 const { data, loading, error, reload } = useResource<{ tasks: Task[] }>("/api/inspection-tasks");
 const [pending, setPending] = useState(false); const [message, setMessage] = useState(""); const [status, setStatus] = useState("PENDING");
 async function save(id: string, form?: HTMLFormElement) { if (pending) return; const values = form && new FormData(form); setPending(true); setMessage(""); try { await apiRequest("/api/inspection-tasks", jsonRequest(form ? "PATCH" : "DELETE", form ? { id, status: values!.get("status"), response: values!.get("response") } : { id })); setMessage("清查狀態已更新。"); await reload(); } catch (e) { setMessage(e instanceof Error ? e.message : "更新失敗"); } finally { setPending(false); } }
 const tasks = data?.tasks.filter((task) => status === "ALL" || task.status === status) || [];
 return <><div className="admin-toolbar"><label>顯示<select value={status} onChange={(e) => setStatus(e.target.value)}><option value="ALL">全部</option>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><button className="button" disabled={loading || pending} onClick={() => void reload()}>重新整理</button></div><p role="status">{message}</p>{error ? <ResourceError message={error} retry={reload} /> : loading ? <p role="status">載入中…</p> : !tasks.length ? <p>目前沒有符合條件的清查通知。</p> : tasks.map((task) => <article className="card modal-body" key={task.id}><h2>{task.snapshot.recordName}</h2><code style={{ overflowWrap: "anywhere" }}>{task.snapshot.recordType} · {task.snapshot.content}</code><p>{task.snapshot.applicantUnit || "未填單位"} · {task.snapshot.purpose || "未填用途"}</p><small>{task.user.email} · {task.user.name} · {new Date(task.createdAt).toLocaleString("zh-TW")}</small><strong>{labels[task.status] || task.status}</strong>{task.response && <p style={{ whiteSpace: "pre-wrap" }}>{task.response}</p>}{task.respondedAt && <small>處理時間：{new Date(task.respondedAt).toLocaleString("zh-TW")}</small>}{task.status === "PENDING" && task.userId === actorId && <form onSubmit={(e) => { e.preventDefault(); void save(task.id, e.currentTarget); }}><fieldset className="dialog-fields" disabled={pending}><label>確認結果<select name="status"><option value="CONFIRMED">確認仍在使用</option><option value="ISSUE">回報問題</option></select></label><label>說明（回報問題必填）<textarea name="response" maxLength={2000} rows={3} /></label><button className="button primary">送出確認</button></fieldset></form>}{admin && task.status === "PENDING" && <button className="button" disabled={pending} onClick={() => { if (window.confirm("撤回此清查通知？使用者將無法繼續回覆。")) void save(task.id); }}>撤回通知</button>}</article>)}</>;
}
export function AssignInspectionDialog({ record, onClose }: { record: InventoryRecord; onClose: () => void }) {
 const users = useResource<{ users: { id: string; name: string; email: string | null; disabled: boolean }[] }>("/api/users");
 const [pending, setPending] = useState(false); const [error, setError] = useState("");
 return <Dialog title="指派使用者清查" description="所選使用者將能查看此筆 DNS 並回覆。這是站內通知，不會寄送郵件。" pending={pending} onClose={onClose}><form onSubmit={async (e) => { e.preventDefault(); if (pending) return; const values = new FormData(e.currentTarget); setPending(true); setError(""); try { await apiRequest("/api/inspection-tasks", jsonRequest("POST", { userId: values.get("userId"), record: { zoneName: record.zoneName, recordName: record.recordName, recordType: record.recordType, content: record.content } })); onClose(); } catch (e) { setError(e instanceof Error ? e.message : "指派失敗"); } finally { setPending(false); } }}><fieldset className="dialog-fields modal-body" disabled={pending || users.loading}><p>{record.recordName} · {record.recordType}</p><code style={{ overflowWrap: "anywhere" }}>{record.content}</code><label>負責確認的使用者<select name="userId" required defaultValue=""><option value="" disabled>選擇電子郵件／姓名</option>{users.data?.users.filter((user) => !user.disabled).map((user) => <option key={user.id} value={user.id}>{user.email || "未提供郵件"} · {user.name}</option>)}</select></label>{users.error && <ResourceError message={users.error} retry={users.reload} />}{error && <p role="alert">{error}</p>}<button className="button primary" disabled={!users.data || pending}>建立站內清查通知</button></fieldset></form></Dialog>;
}
