CREATE TYPE "GlobalRole" AS ENUM ('USER', 'SUPER_ADMIN');
CREATE TYPE "ZoneRole" AS ENUM ('VIEWER', 'EDITOR', 'ADMIN');
CREATE TABLE "User" ("id" TEXT PRIMARY KEY,"name" TEXT,"email" TEXT NOT NULL,"emailVerified" TIMESTAMP(3),"image" TEXT,"globalRole" "GlobalRole" NOT NULL DEFAULT 'USER',"lastLoginAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE TABLE "Account" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL,"type" TEXT NOT NULL,"provider" TEXT NOT NULL,"providerAccountId" TEXT NOT NULL,"refresh_token" TEXT,"access_token" TEXT,"expires_at" INTEGER,"token_type" TEXT,"scope" TEXT,"id_token" TEXT,"session_state" TEXT);
CREATE UNIQUE INDEX "Account_provider_providerAccountId_key" ON "Account"("provider","providerAccountId");
ALTER TABLE "Account" ADD CONSTRAINT "Account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
CREATE TABLE "Session" ("id" TEXT PRIMARY KEY,"sessionToken" TEXT NOT NULL,"userId" TEXT NOT NULL,"expires" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "Session_sessionToken_key" ON "Session"("sessionToken");
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
CREATE TABLE "VerificationToken" ("identifier" TEXT NOT NULL,"token" TEXT NOT NULL,"expires" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "VerificationToken_token_key" ON "VerificationToken"("token");
CREATE UNIQUE INDEX "VerificationToken_identifier_token_key" ON "VerificationToken"("identifier","token");
CREATE TABLE "ZonePermission" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL,"zoneName" TEXT NOT NULL,"role" "ZoneRole" NOT NULL,"resourcePattern" TEXT,"allowedRecordTypes" TEXT[] DEFAULT ARRAY[]::TEXT[],"expiresAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "ZonePermission_userId_zoneName_key" ON "ZonePermission"("userId","zoneName");
CREATE INDEX "ZonePermission_zoneName_idx" ON "ZonePermission"("zoneName");
ALTER TABLE "ZonePermission" ADD CONSTRAINT "ZonePermission_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
CREATE TABLE "Group" ("id" TEXT PRIMARY KEY,"name" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "Group_name_key" ON "Group"("name");
CREATE TABLE "GroupMember" ("id" TEXT PRIMARY KEY,"groupId" TEXT NOT NULL,"userId" TEXT NOT NULL);
CREATE UNIQUE INDEX "GroupMember_groupId_userId_key" ON "GroupMember"("groupId","userId");
ALTER TABLE "GroupMember" ADD CONSTRAINT "GroupMember_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "Group"("id") ON DELETE CASCADE;
ALTER TABLE "GroupMember" ADD CONSTRAINT "GroupMember_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
CREATE TABLE "GroupZonePermission" ("id" TEXT PRIMARY KEY,"groupId" TEXT NOT NULL,"zoneName" TEXT NOT NULL,"role" "ZoneRole" NOT NULL,"resourcePattern" TEXT,"expiresAt" TIMESTAMP(3));
CREATE UNIQUE INDEX "GroupZonePermission_groupId_zoneName_key" ON "GroupZonePermission"("groupId","zoneName");
ALTER TABLE "GroupZonePermission" ADD CONSTRAINT "GroupZonePermission_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "Group"("id") ON DELETE CASCADE;
CREATE TABLE "AuditLog" ("id" TEXT PRIMARY KEY,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"userId" TEXT,"userEmail" TEXT NOT NULL,"zone" TEXT NOT NULL,"recordName" TEXT,"recordType" TEXT,"action" TEXT NOT NULL,"oldValue" JSONB,"newValue" JSONB,"ipAddress" TEXT,"userAgent" TEXT,"requestId" TEXT,"success" BOOLEAN NOT NULL,"errorMessage" TEXT);
CREATE INDEX "AuditLog_createdAt_idx" ON "AuditLog"("createdAt");
CREATE INDEX "AuditLog_zone_createdAt_idx" ON "AuditLog"("zone","createdAt");
CREATE INDEX "AuditLog_userId_createdAt_idx" ON "AuditLog"("userId","createdAt");
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL;
CREATE TABLE "SystemSetting" ("key" TEXT PRIMARY KEY,"value" JSONB NOT NULL,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "ProtectedRecordRule" ("id" TEXT PRIMARY KEY,"zonePattern" TEXT NOT NULL,"recordPattern" TEXT NOT NULL,"recordType" TEXT NOT NULL,"minimumRole" "ZoneRole" NOT NULL DEFAULT 'ADMIN',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "ProtectedRecordRule_zonePattern_recordPattern_recordType_key" ON "ProtectedRecordRule"("zonePattern","recordPattern","recordType");
CREATE TABLE "RecordTypePolicy" ("id" TEXT PRIMARY KEY,"zoneName" TEXT NOT NULL,"role" "ZoneRole" NOT NULL,"allowedTypes" TEXT[] NOT NULL,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "RecordTypePolicy_zoneName_role_key" ON "RecordTypePolicy"("zoneName","role");
