CREATE TYPE "UnitStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');
ALTER TABLE "DnsUnit" ADD COLUMN "status" "UnitStatus" NOT NULL DEFAULT 'PENDING',
ADD COLUMN "reviewedBy" TEXT, ADD COLUMN "reviewedAt" TIMESTAMP(3), ADD COLUMN "reviewNote" TEXT;
