import { beforeEach, expect, it, vi } from "vitest";
vi.mock("server-only", () => ({}));
vi.mock("@/lib/db/client", () => ({ db: {} }));
vi.mock("@/lib/db/local-store", () => ({ isLocalDemo: () => true, localDocument: vi.fn() }));
vi.mock("@/lib/auth/session", () => ({ requireActor: vi.fn(), AuthError: class extends Error {} }));
vi.mock("@/lib/audit/service", () => ({ logAuditEvent: vi.fn(async () => {}) }));
vi.mock("@/lib/dns/lock", () => ({ withDnsZoneLock: async (_zone: string, fn: () => Promise<unknown>) => fn() }));
vi.mock("@/lib/inventory/service", () => ({ describeRecords: vi.fn() }));
vi.mock("@/lib/powerdns/client", () => ({ powerdns: { getZone: vi.fn(), replaceRRSet: vi.fn(), deleteRRSet: vi.fn(), deleteZone: vi.fn() } }));
import { localDocument } from "@/lib/db/local-store";
import { requireActor } from "@/lib/auth/session";
import { logAuditEvent } from "@/lib/audit/service";
import { powerdns } from "@/lib/powerdns/client";
import { assertDeletionPassword, saveDeletionPassword, deletionProtectionStatus } from "@/lib/security/deletion-protection";
import { GET, PUT } from "@/app/api/admin/deletion-protection/route";
import { DELETE, PATCH } from "@/app/api/zones/[zone]/records/route";
import { DELETE as deleteZone } from "@/app/api/zones/[zone]/route";
import { rrsetHash } from "@/lib/dns/rrset";
import type { Actor, Zone } from "@/lib/dns/types";
const owner: Actor = { id: "owner", email: "owner@example.com", globalRole: "SUPER_ADMIN", portalIdentifier: "115502532", zoneRoles: {} };
const admin: Actor = { ...owner, id: "admin", globalRole: "ADMIN", portalIdentifier: null };
const password = "secret-delete-1234";
let documents: Record<string, unknown>;
let zone: Zone;
const context = { params: Promise.resolve({ zone: "example.com." }) };
const request = (method: string, body: unknown, path = "zones/example.com/records", origin = "http://localhost") => new Request(`http://localhost/api/${path}`, { method, headers: { Origin: origin, "Content-Type": "application/json" }, body: JSON.stringify(body) });
const configure = () => saveDeletionPassword(owner, { password, confirmation: password, expectedUpdatedAt: null });
beforeEach(() => {
  vi.clearAllMocks(); documents = {};
  vi.mocked(localDocument).mockImplementation(async (name, initial, operation) => { documents[name] ??= await initial(); return operation(documents[name]); });
  vi.mocked(requireActor).mockResolvedValue(admin);
  zone = { id: "example.com.", name: "example.com.", kind: "Native", serial: 1, dnssec: false, rrsets: [{ name: "www.example.com.", type: "A", ttl: 300, records: [{ content: "192.0.2.1", disabled: false }, { content: "192.0.2.2", disabled: false }] }] };
  vi.mocked(powerdns.getZone).mockImplementation(async () => structuredClone(zone));
});
it("restricts configuration to the actual owner, stores only hashes and rejects stale rotations", async () => {
  for (const actor of [admin, { ...owner, portalIdentifier: null }]) await expect(saveDeletionPassword(actor, {})).rejects.toMatchObject({ status: 403 });
  const status = await configure();
  expect(JSON.stringify(documents)).not.toContain(password);
  expect(JSON.stringify(documents)).toContain("scrypt$");
  expect(await deletionProtectionStatus()).toEqual(status);
  await expect(saveDeletionPassword(owner, { password, confirmation: password, expectedUpdatedAt: null })).rejects.toMatchObject({ status: 409 });
  const next = "rotated-delete-1234";
  await saveDeletionPassword(owner, { password: next, confirmation: next, expectedUpdatedAt: status.updatedAt });
  await expect(assertDeletionPassword(admin, password)).rejects.toMatchObject({ status: 403 });
  await expect(assertDeletionPassword(admin, next)).resolves.toBeUndefined();
});
it("fails closed when unset and limits incorrect attempts without leaking secrets", async () => {
  await expect(assertDeletionPassword(admin, password)).rejects.toMatchObject({ status: 409 });
  await configure();
  await expect(assertDeletionPassword(admin, undefined)).rejects.toMatchObject({ status: 403 });
  for (let i = 0; i < 5; i++) await expect(assertDeletionPassword(admin, "wrong")).rejects.toMatchObject({ status: 403 });
  await expect(assertDeletionPassword(admin, password)).rejects.toMatchObject({ status: 429 });
  await expect(assertDeletionPassword(owner, password)).resolves.toBeUndefined();
  const now = Date.now(); const spy = vi.spyOn(Date, "now").mockReturnValue(now + 16 * 60 * 1000);
  try { await expect(assertDeletionPassword(admin, password)).resolves.toBeUndefined(); } finally { spy.mockRestore(); }
});
it("requires confirmation, validates length, protects the API and returns only public status", async () => {
  vi.mocked(requireActor).mockResolvedValue(owner);
  const body = { password, confirmation: password, expectedUpdatedAt: null };
  expect((await PUT(request("PUT", body, "admin/deletion-protection", "https://evil.invalid"))).status).toBe(403);
  for (const invalid of [{ ...body, confirmation: "different-secret" }, { ...body, password: "short" }, { ...body, password: "x".repeat(257) }]) expect((await PUT(request("PUT", invalid))).status).toBe(400);
  expect((await PUT(request("PUT", body))).status).toBe(200);
  const response = await GET();
  expect(response.headers.get("Cache-Control")).toContain("no-store");
  expect(Object.keys(await response.json()).sort()).toEqual(["configured", "updatedAt"]);
  expect(JSON.stringify(vi.mocked(logAuditEvent).mock.calls)).not.toContain(password);
  vi.mocked(requireActor).mockResolvedValue(admin);
  expect((await PUT(request("PUT", body))).status).toBe(403);
  vi.mocked(requireActor).mockResolvedValue({ ...admin, globalRole: "USER" });
  expect((await GET()).status).toBe(403);
});
it("checks the password for each deletion and preserves permission and same-origin boundaries", async () => {
  await configure();
  const body = { name: zone.rrsets[0].name, type: "A", content: "192.0.2.1", expectedHash: rrsetHash(zone.rrsets[0]) };
  for (const deletionPassword of [undefined, "wrong"]) expect((await DELETE(request("DELETE", { ...body, deletionPassword }), context)).status).toBe(403);
  expect(powerdns.replaceRRSet).not.toHaveBeenCalled();
  expect((await DELETE(request("DELETE", { ...body, deletionPassword: password }), context)).status).toBe(200);
  expect(powerdns.replaceRRSet).toHaveBeenCalledWith(zone.name, expect.objectContaining({ records: [{ content: "192.0.2.2", disabled: false }] }));
  expect((await DELETE(request("DELETE", body), context)).status).toBe(403);
  expect((await DELETE(request("DELETE", { ...body, deletionPassword: password }, undefined, "https://evil.invalid"), context)).status).toBe(403);
  vi.mocked(requireActor).mockResolvedValue({ ...admin, globalRole: "USER", zoneRoles: { [zone.name]: "EDITOR" } });
  expect((await DELETE(request("DELETE", { ...body, deletionPassword: password }), context)).status).toBe(404);
  expect(powerdns.replaceRRSet).toHaveBeenCalledOnce();
});
it("prevents removing values through PATCH while allowing TTL-only changes", async () => {
  await configure();
  const body = { name: zone.rrsets[0].name, type: "A", ttl: 600, contents: ["192.0.2.1"], expectedHash: rrsetHash(zone.rrsets[0]) };
  expect((await PATCH(request("PATCH", body), context)).status).toBe(403);
  expect(powerdns.replaceRRSet).not.toHaveBeenCalled();
  expect((await PATCH(request("PATCH", { ...body, contents: ["192.0.2.1", "192.0.2.2"] }), context)).status).toBe(200);
  expect((await PATCH(request("PATCH", { ...body, deletionPassword: password }), context)).status).toBe(200);
});
it("requires both zone authorization, name confirmation and password", async () => {
  await configure();
  const path = "zones/example.com?confirm=example.com";
  expect((await deleteZone(request("DELETE", { deletionPassword: password }, path), context)).status).toBe(404);
  vi.mocked(requireActor).mockResolvedValue(owner);
  expect((await deleteZone(request("DELETE", {}, path), context)).status).toBe(403);
  expect(powerdns.deleteZone).not.toHaveBeenCalled();
  expect((await deleteZone(request("DELETE", { deletionPassword: password }, path), context)).status).toBe(204);
  expect(powerdns.deleteZone).toHaveBeenCalledWith(zone.name);
});
