import { auditMutation } from "@/lib/audit/mutation";
import { describeRecords } from "@/lib/inventory/service";
import { effectiveZoneRole } from "@/lib/auth/permissions";
import { requireActor } from "@/lib/auth/session";
import { canDeleteRecord, canEditRecordType, canManageZone } from "@/lib/auth/permissions";
import { normalizeDnsName, normalizeRecordContent, normalizeZoneName, validateTtl } from "@/lib/dns/names";
import { addRecord, removeRecord, rrsetHash } from "@/lib/dns/rrset";
import type { RRSet } from "@/lib/dns/types";
import { powerdns } from "@/lib/powerdns/client";
import { apiError, ApiError, notFoundUnless } from "@/lib/api/respond";
import { recordDeleteSchema, recordMutationSchema, rrsetReplaceSchema } from "@/lib/validation/api";
import { logAuditEvent } from "@/lib/audit/service";

async function context(params:Promise<{zone:string}>){const actor=await requireActor();const zone=normalizeZoneName(decodeURIComponent((await params).zone));notFoundUnless(canManageZone(actor,zone));return {actor,zone};}
export async function GET(_req:Request,{params}:RouteContext<"/api/zones/[zone]/records">){try{const {actor,zone}=await context(params);const data=await powerdns.getZone(zone);const inventory=await describeRecords(actor,zone,data.rrsets);const ownership=new Map(inventory.map((item)=>[JSON.stringify([item.recordName,item.recordType,item.content]),item.ownership]));return Response.json({rrsets:data.rrsets.map((r)=>({...r,hash:rrsetHash(r),records:r.records.map((record)=>({...record,ownership:ownership.get(JSON.stringify([r.name,r.type,record.content]))}))})),permission:effectiveZoneRole(actor,zone)});}catch(error){return apiError(error);}}
async function POSTHandler(request:Request,{params}:RouteContext<"/api/zones/[zone]/records">){return mutate(request,params,"CREATE_RECORD",async(zone,body)=>{const data=recordMutationSchema.parse(body);const name=normalizeDnsName(data.name,zone);const content=normalizeRecordContent(data.type,data.content);const current=(await powerdns.getZone(zone)).rrsets.find((r)=>r.name===name&&r.type===data.type);if(data.expectedHash&&rrsetHash(current)!==data.expectedHash)throw new ApiError("This RRset changed since you opened it. Refresh and try again.",409);const next=addRecord(current,{name,type:data.type,ttl:validateTtl(data.ttl)},content);return {current,next};});}
async function PATCHHandler(request:Request,{params}:RouteContext<"/api/zones/[zone]/records">){return mutate(request,params,"UPDATE_RECORD",async(zone,body)=>{const data=rrsetReplaceSchema.parse(body);const name=normalizeDnsName(data.name,zone);const all=(await powerdns.getZone(zone)).rrsets;const current=all.find((r)=>r.name===name&&r.type===data.type);if(!current)throw new ApiError("RRset not found",404);if(rrsetHash(current)!==data.expectedHash)throw new ApiError("This RRset changed since you opened it. Refresh and try again.",409);const next:RRSet={name,type:data.type,ttl:validateTtl(data.ttl),records:data.contents.map((content)=>({content:normalizeRecordContent(data.type,content),disabled:false}))};return {current,next};});}
async function DELETEHandler(request:Request,{params}:RouteContext<"/api/zones/[zone]/records">){return mutate(request,params,"DELETE_RECORD",async(zone,body)=>{const data=recordDeleteSchema.parse(body);const name=normalizeDnsName(data.name,zone);const current=(await powerdns.getZone(zone)).rrsets.find((r)=>r.name===name&&r.type===data.type);if(!current)throw new ApiError("RRset not found",404);if(rrsetHash(current)!==data.expectedHash)throw new ApiError("This RRset changed since you opened it. Refresh and try again.",409);const content=data.content?normalizeRecordContent(data.type,data.content):undefined;return {current,next:removeRecord(current,content),type:data.type,name};});}

async function mutate(request:Request,params:Promise<{zone:string}>,action:string,prepare:(zone:string,body:unknown)=>Promise<{current:RRSet|undefined;next:RRSet|undefined;type?:RRSet["type"];name?:string}>){let actor;let zone="";let before;try{({actor,zone}=await context(params));const result=await prepare(zone,await request.json());before=result.current;const type=result.next?.type??result.type??result.current?.type;const name=result.next?.name??result.name??result.current?.name;if(!type||!name)throw new ApiError("Invalid RRset",400);if(action==="DELETE_RECORD"?!canDeleteRecord(actor,zone,type,name):!canEditRecordType(actor,zone,type))notFoundUnless(false);if(result.next)await powerdns.replaceRRSet(zone,result.next);else await powerdns.deleteRRSet(zone,name,type);await logAuditEvent({actor,zone,action,recordName:name,recordType:type,before:result.current,after:result.next,success:true,request});return Response.json({rrset:result.next??null,hash:rrsetHash(result.next)});}catch(error){if(actor)await logAuditEvent({actor,zone,action,before,success:false,errorMessage:error instanceof Error?error.message:"Unknown error",request}).catch(()=>undefined);return apiError(error);}}

export const POST = auditMutation(POSTHandler);
export const PATCH = auditMutation(PATCHHandler);
export const DELETE = auditMutation(DELETEHandler);
