import { auditMutation } from "@/lib/audit/mutation";
import { accountOwnerIdentifier, OWNER_IDENTIFIER } from "@/lib/auth/owner";
import { requireActor } from "@/lib/auth/session";
import { canManagePermissions, canViewZone } from "@/lib/auth/permissions";
import { apiError, ApiError, notFoundUnless } from "@/lib/api/respond";
import { logAuditEvent } from "@/lib/audit/service";
import { db } from "@/lib/db/client";
import { normalizeZoneName } from "@/lib/dns/names";
import { permissionSchema } from "@/lib/validation/api";
import { mockPermissions } from "@/lib/mock/permissions";

async function zoneContext(params:Promise<{zone:string}>){const actor=await requireActor();const zone=normalizeZoneName(decodeURIComponent((await params).zone));notFoundUnless(canViewZone(actor,zone));return{actor,zone};}
export async function GET(_request:Request,{params}:RouteContext<"/api/zones/[zone]/permissions">){try{const{actor,zone}=await zoneContext(params);notFoundUnless(canManagePermissions(actor,zone));if(!process.env.DATABASE_URL)return Response.json({permissions:mockPermissions});const permissions=await db.zonePermission.findMany({where:{zoneName:zone},include:{user:{select:{name:true,email:true,image:true}}},orderBy:{createdAt:"asc"}});return Response.json({permissions});}catch(error){return apiError(error);}}
async function POSTHandler(request:Request,{params}:RouteContext<"/api/zones/[zone]/permissions">){let actor;let zone="";try{({actor,zone}=await zoneContext(params));notFoundUnless(canManagePermissions(actor,zone));const input=permissionSchema.parse(await request.json());if(input.userId==="dev-owner")throw new ApiError("最高使用者受保護，不能變更權限。",403);if(!process.env.DATABASE_URL){const email=input.userEmail??`${input.userId}@example.com`;const permission={id:crypto.randomUUID(),userId:input.userId??email,user:{name:email.split("@")[0],email,image:null},role:input.role,expiresAt:input.expiresAt??null};mockPermissions.push(permission);await logAuditEvent({actor,zone,action:"UPDATE_PERMISSION",after:permission,success:true,request});return Response.json({permission},{status:201});}const user=input.userId?await db.user.findUnique({where:{id:input.userId},include:{accounts:{where:{provider:{in:["ncu-portal","logto"]}},select:{provider:true,providerAccountId:true}}}}):await db.user.findUnique({where:{email:input.userEmail!.toLowerCase()},include:{accounts:{where:{provider:{in:["ncu-portal","logto"]}},select:{provider:true,providerAccountId:true}}}});if(!user)throw new ApiError("User not found",404);if(accountOwnerIdentifier(user.accounts)===OWNER_IDENTIFIER)throw new ApiError("最高使用者受保護，不能變更權限。",403);const previous=await db.zonePermission.findUnique({where:{userId_zoneName:{userId:user.id,zoneName:zone}}});const permission=await db.zonePermission.upsert({where:{userId_zoneName:{userId:user.id,zoneName:zone}},update:{role:input.role,expiresAt:input.expiresAt?new Date(input.expiresAt):null,resourcePattern:input.resourcePattern},create:{userId:user.id,zoneName:zone,role:input.role,expiresAt:input.expiresAt?new Date(input.expiresAt):null,resourcePattern:input.resourcePattern},include:{user:{select:{name:true,email:true,image:true}}}});await logAuditEvent({actor,zone,action:"UPDATE_PERMISSION",before:previous,after:permission,success:true,request});return Response.json({permission},{status:201});}catch(error){if(actor)await logAuditEvent({actor,zone,action:"UPDATE_PERMISSION",success:false,errorMessage:error instanceof Error?error.message:"Unknown error",request}).catch(()=>undefined);return apiError(error);}}

export const POST = auditMutation(POSTHandler);
